---
minimum_pre_commit_version: 2.18.1

repos:

# commit-msg hooks
# ----------

# Conventional Commit message checker (commitizen)
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.23.0
  hooks:
  - id: commitizen
    stages:
    - commit-msg

# pre-commit hooks
# ----------

# Standard pre-commit rules
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-toml
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: trailing-whitespace
    args:
    - --markdown-linebreak-ext=md
# Black (uncompromising) Python code formatter
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
    args:
    - --target-version
    - py311
# MyPy
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.942
  hooks:
  - id: mypy
    files: ^decoder
    args:
    - --install-types
    - --non-interactive
# YAML Lint
- repo: https://github.com/adrienverge/yamllint
  rev: v1.26.3
  hooks:
  - id: yamllint
# Pyroma
- repo: https://github.com/regebro/pyroma
  rev: "4.0"
  hooks:
  - id: pyroma

# Local hooks (requires a suitable env)
# -----
# The following expect 'pip install -r requirements.txt'

# Pylint
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    files: ^decoder/.*\.py$
